blog/urls.py
from django.urls import path
from . import views
app_name = "blog_app"
urlpatterns = [
    path('', views.index, name='home'),
    path('category/<slug:slug>/', views.blog_column, name='category'),

    path('post/<slug:slug>/', views.post, name='post-detail'),
    path('post/<id>/update/', views.post_update, name='post-update'),
    path('post/<id>/delete/', views.post_delete, name='post-delete'),
    path('create/', views.post_create, name='post-create'),
    path('search/', views.search, name='search'),
    path('contact/', views.contact, name='contact'),

]

reverence/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('blog.urls', namespace="blog_app")),
    path('accounts/', include('allauth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from typing import ChainMap
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.fields import SlugField
from django.db.models.signals import pre_save
from django.urls import reverse
from tinymce.models import HTMLField
from reverence.utils import unique_slug_generator

User = get_user_model()


class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(
        'Post',  on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    timestamp = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()
    post = models.ForeignKey(
        'Post', related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    thumbnail = models.ImageField()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    title = models.CharField(max_length=30)
    image = models.ImageField(null=True)
    slug = models.SlugField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog_app:category", kwargs={"slug": self.slug})


class Post(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField()
    description = models.CharField(max_length=200, default="I love you ")
    slug = models.SlugField(max_length=200, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    content = HTMLField()

    categories = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog_app:post-detail", kwargs={"slug": self.slug})

    @property
    def get_comments(self):
        return self.comments.all().order_by('-timestamp')

    @property
    def get_update(self):
        return reverse("blog_app:post-update", kwargs={"id": self.pk})

    @property
    def get_delete(self):
        return reverse("blog_app:post-delete", kwargs={"id": self.pk})

    @property
    def view_count(self):
        return PostView.objects.filter(post=self).count()

    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count()


class SignUp(models.Model):
    email = models.EmailField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email


class Qoutes(models.Model):
    author = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return self.author


def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


def slug_cat_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(slug_generator, sender=Post)
pre_save.connect(slug_cat_generator, sender=Category)

blog/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import *


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )

    class Meta:
        model = Post
        fields = ('title', 'overview', 'content', 'thumbnail',
                  'categories')


class CommentForm(forms.ModelForm):
    comment = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Leave your Comment',
                'class': 'form-control',
                'rows': '4',
                'cols': '10',
                'required': True,

            }
        )
    )
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Full Name e.g. Jason Doe',
                'class': 'form-control',
                'required': True,
                'name': 'name',


            }
        )
    )
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Email Address e.g. Jason@email.com',
                'class': 'form-control',
                'name': 'email',
                'required': True,


            }
        )
    )

    class Meta:
        model = Comment
        fields = ('name', 'email', 'comment')

blog/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.db.models import Count, Q
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import *
import random
import urllib.parse
# Create your views here.


def get_author(user):
    qs = Author.objects.filter(user=user)
    if qs.exists():
        return qs[0]
    return None


def get_category_count():
    queryset = Post.objects.values(
        'categories__title', 'categories__image').annotate(Count('categories__title')).order_by('categories__title')[0:3]
    return queryset


def index(request):
    category_title = get_category_count()
    cat_trend = Category.objects.order_by('-image')

    post = Post.objects.all()
    latest = Post.objects.order_by("-timestamp")[1:4]

    first_post = Post.objects.first()
    category = Category.objects.all()
    qoute = Qoutes.objects.first()

    paginator = Paginator(post, 5)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)

    try:
        paginated_qs = paginator.page(page)
    except PageNotAnInteger:
        paginated_qs = paginator.page(1)
    except EmptyPage:
        paginated_qs = paginator.page(paginator.num_pages)

    if request.method == 'POST':
        email = request.POST.get('email')
        new_signup = SignUp()
        new_signup.email = email
        new_signup.save()

    context = {
        'queryset': paginated_qs,
        'paginator': paginator,
        'page_request_var': page_request_var,
        'latest_post': latest,
        'category': category,
        'cat_trend': cat_trend,
        'category_title': category_title,
        'first_post': first_post,
        'qoutes': qoute
    }
    return render(request, 'blog/index.html', context)


def nav(request):
    category = Category.objects.all()

    context = {
        'category': category
    }
    return render(request, 'blog/base.html', context)


def blog_column(request, slug):
    category_title = get_category_count()
    cat_trend = Category.objects.order_by('-image')
    latest = Post.objects.order_by("-timestamp")[1:4]
    cat = Post.objects.filter(categories__slug=slug)
    if cat.exists():
        paginator = Paginator(cat, 5)
        page_request_var = 'page'
        page = request.GET.get(page_request_var)

        try:
            paginated_qs = paginator.page(page)
        except PageNotAnInteger:
            paginated_qs = paginator.page(1)
        except EmptyPage:
            paginated_qs = paginator.page(paginator.num_pages)
    else:
        return HttpResponse('<h1>No category found </h1>')

    category = Category.objects.all()

    context = {
        'queryset': paginated_qs,
        'category': cat,
        'category': category,
        'paginator': paginator,
        'latest_post': latest,
        'cat_trend': cat_trend,
        'page_request_var': page_request_var

    }
    return render(request, 'blog/blog_column.html', context)


def search(request):
    post_list = Post.objects.all()
    category_title = get_category_count()
    latest = Post.objects.order_by("-timestamp")[1:4]
    cat_trend = Category.objects.order_by('-image')
    query = request.GET.get('q')
    if query:
        post_list = post_list.filter(
            Q(title__icontains=query) |
            Q(description__icontains=query) |
            Q(content__icontains=query)
        ).distinct()

    paginator = Paginator(post_list, 5)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)

    try:
        paginated_qs = paginator.page(page)
    except PageNotAnInteger:
        paginated_qs = paginator.page(1)
    except EmptyPage:
        paginated_qs = paginator.page(paginator.num_pages)

    context = {
        'queryset': paginated_qs,
        'page_request_var': page_request_var,
        'latest_post': latest,
        'paginator': paginator,
        'cat_trend': cat_trend,
        'category_title': category_title
    }
    return render(request, 'blog/search.html', context)


def post(request, slug):
    post = Post.objects.filter(slug=slug)
    share_string = urllib.parse.quote("ghhhhhhgk", safe='')
    category_title = get_category_count()
    latest = Post.objects.order_by("-timestamp")[1:4]
    cat_trend = Category.objects.order_by('-image')
    if post.exists():
        post = post.first()
    else:
        return HttpResponse("<h1> Page not Found </h1>")

    category = Category.objects.all()
    qoute = Qoutes.objects.first()
    if request.user.is_authenticated:
        PostView.objects.get_or_create(user=request.user, post=post)

    form = CommentForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():

            form.instance.post = post
            form.save()
            return redirect(reverse("blog_app:post-detail", kwargs={
                'slug': post.slug
            }))

    context = {
        'post': post,
        'share_string': share_string,
        'categories': category,
        'form': form,
        'category_title': category_title,
        'cat_trend': cat_trend,
        'latest_post': latest,

        'category': category,
        'qoutes': qoute
    }
    return render(request, 'blog/post1.html', context)


def post_update(request, id):
    post = get_object_or_404(Post, id=id)
    title = 'update'
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    author = get_author(request.user)
    if request.method == 'POST':
        if form.is_valid():
            form.instance.author = author
            form.save()
            return redirect(reverse(
                "blog_app:post-detail",
                kwargs={
                    'id': form.instance.id
                }
            ))
    context = {
        'form': form,
        'title': title
    }
    return render(request, 'blog/post_create.html', context)


def post_delete(request, id):
    post = get_object_or_404(Post, id=id)
    post.delete()
    return redirect(reverse(
        "blog_app:blog_column"))

    return render(request, 'blog/post_create.html', context)


def post_create(request):
    title = 'create'
    form = PostForm(request.POST or None, request.FILES or None)
    author = get_author(request.user)
    if request.method == 'POST':
        if form.is_valid():
            form.instance.author = author
            form.save()
            return redirect(reverse(
                "blog_app:post-detail",
                kwargs={
                    'id': form.instance.id
                }
            ))
    context = {
        'form': form,
        'title': title
    }
    return render(request, 'blog/post_create.html', context)


def contact(request):
    category = Category.objects.all()
    cat_trend = Category.objects.order_by('-image')

    context = {
        'category': category,
        'cat_trend': cat_trend,

    }
    return render(request, 'blog/contact.html', context)

templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta
      name="description"
      content="Reverence is  a lively and
      thought-provoking blog focused on dissecting the word of God, acts of
      charity and pure worship."
    />
    <meta
      name="keywords"
      content="Reverence, , hope,Christianity,Romans 12 v 12,Philippians 1 v 21-22,inspiration,worship,blog,testimony,"
    />
    <meta name="author" content="Vanessa Banda-Chidhumo" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="robots" content="all,follow" />
    <title>{% block head_title %}{% endblock %}</title>
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href=" {% static 'img/favicon/apple-touch-icon.png' %}  "
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="{% static 'img/favicon/favicon-32x32.png' %} "
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="{% static 'img/favicon/favicon-16x16.png' %}  "
    />
    <link rel="manifest" href="{% static 'img/favicon/site.webmanifest' %} " />
    {% include 'blog/stylesheet.html' %}
  </head>
  <body>
    {% include 'blog/nav.html'%} {% block content %} {% endblock content %} {% include 'blog/footer.html' %} {% include 'blog/scripts.html' %}
  </body>
</html>

templates/blog/blog_column.html
{% extends 'blog/base.html' %} {% load static %} {% load i18n %} 
{% block head_title %}{% trans "Reverence | Post" %}{% endblock %}  {% block content %}
<section class="py-5">
  <div class="container py-4">
    <div class="row">
      <!-- Blog listing-->
      <div class="col-lg-9 mb-5 mb-lg-0">
        <div class="row">
          {% for post in queryset %}
          <div class="col-lg-6 mb-5">
            <a
              class="d-block post-trending mb-4"
              href="{{post.get_absolute_url}}"
              ><img class="img-fluid w-100" src="{{post.thumbnail.url}}" alt=""
            /></a>
            <ul class="list-inline">
              <li class="list-inline-item mr-2">
                <a class="category-link font-weight-normal" href="#"
                  >{{post.categories}}</a
                >
              </li>
              <li class="list-inline-item mx-2">
                <a class="text-uppercase meta-link font-weight-normal" href="#">
                  {{post.author}}</a
                >
              </li>
              <li class="list-inline-item mx-2">
                <a class="text-uppercase meta-link font-weight-normal" href="#"
                  >{{post.timestamp|date:"d M Y"}}</a
                >
              </li>
            </ul>
            <h2 class="h3 mb-4">
              <a class="d-block reset-anchor" href="{{post.get_absolute_url}}"
                >{{post.title}}</a
              >
            </h2>
            <p class="text-muted">{{post.description|truncatewords:30}}</p>
            <a
              class="btn btn-link p-0 read-more-btn"
              href="{{post.get_absolute_url}}"
              ><span>Read more</span><i class="fas fa-long-arrow-alt-right"></i
            ></a>
          </div>

          {% endfor %}
        </div>
        <!-- Pagination-->
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            {% if queryset.has_previous %}
            <li class="page-item">
              <a
                class="page-link"
                href="?{{ page_request_var}}={{queryset.previous_page_number}}"
                >&laquo;</a
              >
            </li>
            {% endif %}

	 {% for i in paginator.page_range %}
		 {% if queryset.number == i %}
		    <li class="page-item active">
		      <a class="page-link" href="?{{ page_request_var}}={{i}}">{{i}}</a>
		    </li>
		    {% else %}
		    <li class="page-item">
		      <a class="page-link" href="?{{ page_request_var}}={{i}}">{{i}}</a>
		    </li>

		    {% endif %} 
	{% endfor %} 
	{% if queryset.has_next %}
            <li class="page-item">
              <a
                class="page-link"
                href="?{{ page_request_var}}={{queryset.next_page_number}}"
                >&raquo;</a
              >
            </li>
            {% endif %}
          </ul>
        </nav>
      </div>
      <!-- Blog sidebar-->
      <div class="col-lg-3">
        {% include 'blog/sidebar.html' %}
        <!-- Ad-->
        <div class="card rounded-0 border-0 mb-4">
          <div class="card-body p-0">
            <a class="d-block" href="#"
              ><img
                class="img-fluid"
                src="/static/img/banner/banner-03.jpg"
                alt=""
            /></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/blog/blog_row.html
{% extends 'blog/base.html' %}{% load static %} {% load i18n %} 
{% block head_title %}{% trans "Reverence | Post" %}{% endblock %}  {% block content %}
<section class="py-5">
  <div class="container py-4">
    <div class="row">
      <!-- Blog listing-->
      <div class="col-lg-9 mb-5 mb-lg-0">
        <div class="row">
          {% for post in queryset %}

          <div class="col-lg-6 mb-5">
            <a
              class="d-block post-trending mb-4"
              href="{{post.get_absolute_url}}"
              ><img class="img-fluid w-100" src="{{post.thumbnail.url}}" alt=""
            /></a>
            <ul class="list-inline">
              <li class="list-inline-item mr-2">
                {% for cat in post.categories.all %}

                <a class="category-link font-weight-normal" href="#">{{cat}}</a>

                {% endfor %}
              </li>
              <li class="list-inline-item mx-2">
                <a class="text-uppercase meta-link font-weight-normal" href="#"
                  >{{post.author.user.username}}</a
                >
              </li>
              <li class="list-inline-item mx-2">
                <a class="text-uppercase meta-link font-weight-normal" href="#"
                  >{{post.timestamp|date:"d M Y"}}</a
                >
              </li>
            </ul>
            <h2 class="h3 mb-4">
              <a class="d-block reset-anchor" href="{{post.get_absolute_url}}"
                >{{post.title}}</a
              >
            </h2>
            <p class="text-muted">{{post.description:truncatewords:30}}</p>
            <a
              class="btn btn-link p-0 read-more-btn"
              href="{{post.get_absolute_url}}"
              ><span>Read more</span><i class="fas fa-long-arrow-alt-right"></i
            ></a>
          </div>
          {% endfor %}
        </div>
        <!-- Pagination-->
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            {% if queryset.has_previous %}
            <li class="page-item">
              <a
                class="page-link"
                href="?{{ page_request_var}}={{queryset.previous_page_number}}"
                >&laquo;</a
              >
            </li>
            {% endif %} 

	{% for i in paginator.page_range %} 
		{% if queryset.number == i %}
		    <li class="page-item active">
		      <a class="page-link" href="?{{ page_request_var}}={{i}}">{{i}}</a>
		    </li>
		    {% else %}
		    <li class="page-item">
		      <a class="page-link" href="?{{ page_request_var}}={{i}}">{{i}}</a>
		    </li>

		    {% endif %} {% endfor %}
		 {% if queryset.has_next %}
		    <li class="page-item">
		      <a
		        class="page-link"
		        href="?{{ page_request_var}}={{queryset.next_page_number}}"
		        >&raquo;</a
		      >
		    </li>
            {% endif %}
          </ul>
        </nav>
      </div>
      <!-- Blog sidebar-->
      <div class="col-lg-3">
        {% include 'blog/sidebar.html' %}
        <!-- Ad-->
        <div class="card rounded-0 border-0 mb-4">
          <div class="card-body p-0">
            <a class="d-block" href="#"
              ><img class="img-fluid" src="img/banner.jpg" alt=""
            /></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/blog/nav.html
{% load static %}
<header class="header">
  <nav class="navbar navbar-expand-lg navbar-light py-4 index-forward bg-white">
    <div
      class="container d-flex justify-content-center justify-content-lg-between align-items-center"
    >
      <ul class="list-inline small mb-0 text-dark d-none d-lg-block">
        <li class="list-inline-item">
          <a class="reset-anchor" href="#"><i class="fab fa-facebook-f"></i></a>
        </li>
        <li class="list-inline-item">
          <a class="reset-anchor" href="#"><i class="fab fa-twitter"></i></a>
        </li>
        <li class="list-inline-item">
          <a class="reset-anchor" href="https://www.instagram.com/p/CQ33ZKRj1-7/?utm_medium=copy_link"><i class="fab fa-instagram"></i></a>
        </li>
        <li class="list-inline-item">
          <a class="reset-anchor" href="#"><i class="fab fa-linkedin"></i></a>
        </li>
        <li class="list-inline-item">
          <a class="reset-anchor" href="https://youtube.com/channel/UCVfb5F2OsOM_t_sKx4Xmurw"><i class="fab fa-youtube"></i></a>
        </li>
      </ul>
      <a class="navbar-brand" href="{% url 'blog_app:home' %}"
        ><img src="{% static 'img/logo2.jpg' %} " alt="logo" width="150" /></a
      >
      
      
      <a
        class="reset-anchor text-small mb-0 h6 d-none d-lg-block"
        href="mailto:Juliette@email.com"
        ><i class="far fa-envelope mr-2 text-primary"></i>info@reverence.co.zw</a
      >
      
      
    </div>
  </nav>
  <nav
    class="navbar navbar-expand-lg navbar-light border-top border-bottom border-light"
  >
    <div class="container">
      <ul class="list-inline small mb-0 text-dark d-block d-lg-none">
        <li class="list-inline-item">
          <a class="reset-anchor" href="#"><i class="fab fa-facebook-f"></i></a>
        </li>
        <li class="list-inline-item">
          <a class="reset-anchor" href="#"><i class="fab fa-twitter"></i></a>
        </li>
        <li class="list-inline-item">
          <a class="reset-anchor" href="#"><i class="fab fa-instagram"></i></a>
        </li>
        <li class="list-inline-item">
          <a class="reset-anchor" href="#"><i class="fab fa-linkedin"></i></a>
        </li>
        <li class="list-inline-item">
          <a class="reset-anchor" href="#"><i class="fab fa-youtube"></i></a>
        </li>
      </ul>
      <button
        class="navbar-toggler navbar-toggler-right"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span></span><span></span><span></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item">
            <!-- Navbar link--><a
              class="nav-link active"
              href="{% url 'blog_app:home' %}"
              >Home</a
            >
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              id="listingVariants"
              href="#"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
              >Categories</a
            >
            <div class="dropdown-menu mt-2" aria-labelledby="listingVariants">

            {% for cat in category.all  %}
             <a class="dropdown-item"  href="{{cat.get_absolute_url}}">{{cat.title}}</a>
            
            {% endfor %}
            
              
              
             
            </div>
          </li>
          
          
          </li>
          <li class="nav-item">
            <!-- Navbar link--><a
              class="nav-link "
              href="{% url 'blog_app:contact' %}"
              >Contact</a
            >
          </li>
          
        </ul>
        
      </div>
    </div>
  </nav>
</header>

templates/blog/sidebar.html
{% load static %}
<style>
  .widget.search {
    margin-bottom: 30px;
  }
  .widget.search .form-group {
    position: relative;
  }

  .widget.search input {
    width: 100%;
    height: 40px;
    line-height: 40px;
    border: none;
    border-bottom: 1px solid #ddd;
    font-size: 0.95em;
    font-family: "Open Sans", sans-serif;
    font-weight: 400;
    background: none;
  }

  .widget.search input::-moz-placeholder {
    color: #aaa;
    font-family: "Open Sans", sans-serif;
  }

  .widget.search input::-webkit-input-placeholder {
    color: #aaa;
    font-family: "Open Sans", sans-serif;
  }

  .widget.search input:-ms-input-placeholder {
    color: #aaa;
    font-family: "Open Sans", sans-serif;
  }

  .widget.search .submit {
    height: 40px;
    padding: 0;
    line-height: 40px;
    background: none;
    border: none;
    color: #555;
    font-size: 0.9em;
    position: absolute;
    top: 0;
    right: 0;
  }
</style>
<!-- About category-->
<div class="card rounded-0 border-0 bg-light mb-4 py-lg-4">
  <div class="card-body text-center">
    <h2 class="h3 mb-3">About me</h2>
    <img
      class="rounded-circle mb-3"
      src="{% static 'img/van/third.jpg' %}  "
      alt="..."
      width="100"
    />
    <p class="text-small text-muted">
      My name is Vanessa Banda-Chidhumo. Welcome to Reverence, a lively and
      thought-provoking blog focused on dissecting the word of God, acts of
      charity and pure worship.
    </p>
    <ul class="list-inline small mb-0 text-dark">
      <li class="list-inline-item">
        <a class="reset-anchor" href="#"><i class="fab fa-facebook-f"></i></a>
      </li>
      <li class="list-inline-item">
        <a class="reset-anchor" href="https://www.facebook.com/vanessa.banda.92"
          ><i class="fab fa-twitter"></i
        ></a>
      </li>
      <li class="list-inline-item">
        <a class="reset-anchor" href="https://www.instagram.com/van_chid/"
          ><i class="fab fa-instagram"></i
        ></a>
      </li>
      <li class="list-inline-item">
        <a class="reset-anchor" href="#"><i class="fab fa-linkedin"></i></a>
      </li>
      <li class="list-inline-item">
        <a class="reset-anchor" href="#"><i class="fab fa-youtube"></i></a>
      </li>
    </ul>
  </div>
</div>

<div class="widget search">
  <header>
    <h2 class="h5 mb-3">Search Blog</h2>
  </header>
  <form action="{% url 'blog_app:search' %}" class="search-form">
    <div class="form-group">
      <input type="text" name="q" placeholder="What are you looking for?" />
      <button type="submit" class="submit">
        <i class="fa fa-search" aria-hidden="true"></i>
      </button>
    </div>
  </form>
</div>
<!-- Recent posts-->

<div class="card rounded-0 border-0 mb-4">
  <a href="{{latest.get_absolute_url}}">
    <div class="card-body p-0">
      <h2 class="h5 mb-3">Recent posts</h2>
      {% for latest in latest_post %}
      <div class="media mb-3">
        <a class="d-block" href="{{latest.get_absolute_url}}"
          ><img
            class="img-fluid"
            src="{{latest.thumbnail.url}}  "
            alt=""
            width="70"
        /></a>
        <div class="media-body ml-3">
          <h6>
            <a class="reset-anchor" href="{{latest.get_absolute_url}}"
              >{{latest.title}}</a
            >
          </h6>
          <p class="text-small text-muted line-height-sm mb-0">
            {{latest.description|truncatewords:'5' }}
          </p>
        </div>
      </div>
      {% endfor %}
    </div>
  </a>
</div>
<!-- Categories-->
<div class="card rounded-0 border-0 mb-4">
  <div class="card-body p-0">
    <h2 class="h5 mb-3">Trending categories</h2>
    {% for cat in cat_trend.all|slice:'0:3' %}
    <a
      class="category-block category-block-sm bg-center bg-cover mb-2"
      style="background: url({{cat.image.url}})"
      href="{{cat.get_absolute_url}}"
      ><span class="category-block-title">{{cat.title}}</span></a
    >

    {% endfor %}
  </div>
</div>
<!-- Tags-->
<div class="card rounded-0 border-0 mb-4">
  <div class="card-body p-0">
    <h2 class="h5 mb-3">Tags cloud</h2>

    <ul class="list-inline">
      {% for cat in category.all %}
      <li class="list-inline-item my-1 mr-2">
        <a class="sidebar-tag-link" href="{{cat.get_absolute_url}}">{{cat}}</a>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>